update compile script to throw out ImportPath of '.'

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -173,6 +173,11 @@ GOROOT=$cache/$ver/go export GOROOT
 GOPATH=$build/.heroku/go export GOPATH
 PATH=$GOROOT/bin:$PATH
 
+if [ $name == "." ] 
+then 
+	echo -e "Detected an ImportPath of "." in Godeps.json, a full import path for this application is required."
+	exit 1
+fi
 p=$GOPATH/src/$name
 mkdir -p $p
 cp -R $build/* $p
