Fail compilation for applications who have an ImportPath of . in Godeps.json

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -173,6 +173,12 @@ GOROOT=$cache/$ver/go export GOROOT
 GOPATH=$build/.heroku/go export GOPATH
 PATH=$GOROOT/bin:$PATH
 
+if [ $name == "." ] 
+then 
+	echo -e "Detected an ImportPath of "." in Godeps.json, a full ImportPath is required."
+	echo -e "Change \"ImportPath\": \".\" to \"ImportPath\": \"github.com/username/application_name\""
+	exit 1
+fi
 p=$GOPATH/src/$name
 mkdir -p $p
 cp -R $build/* $p
